Public class Constants {

Public static final integer DEFAULT_ROWS = 5;
Public static final string SELECT_ONE = System.Label.SELECT_ONE;
Public static final string INVENTORY_LEVEL_LOW =System.Label.INVENTORY_LEVEL_LOW;
Public static  final List<Schema.PicklistEntry> PRODUCT_FAMILY = product2.Family.getDescribe().getPicklistValues();
Public static final string DRAFT_ORDER_STATUS ='Draft';
Public static final string ACTIVATED_ORDER_STATUS='Activated';
Public static final string INVENTORY_ANNOUNCEMENTS ='Inventory Announcements';
Public static final string ERROR_MESSAGE ='An error has occurred, please take a screenshot with the URL and send it to IT';
public static final string STANDARD_PRICEBOOK_ID='01s28000003tdblAAA';
public static final string Name='Name';


}