Public class xmlparse {

 /*     string xml='<Details><Result>Failed</Result><call><Name>n1</Name><Reason>r1</Reason></call><call><Name>n2</Name><Reason>r2</Reason></call></Details>';
      Map<string,string> callreasonmap = new Map<string,string>();
      Dom.Document doc = new Dom.Document();
       doc.load(xml);
       Dom.XMLNode Details = doc.getRootElement();
        String Result = Details.getChildElement('Result', null).getText();
        //Dom.XMLNode Call = Details.getChildElement('call', null);
        
        // print out specific elements
         for(Dom.XMLNode delements : Details.getChildElements()) {
          if(delements.getName()!='Result') {
          system.debug(delements);
          system.debug(delements.getChildElement('Name',null).getText());
          system.debug(delements.getChildElement('Reason',null).getText());
          callreasonmap.put(delements.getChildElement('Name',null).getText(),delements.getChildElement('Reason',null).getText());
          
          }
          
          
           
        }
        
        system.debug(callreasonmap);*/
        
      
       


}